version: '3'
services:
  PostgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    networks:
      - Wow


  back:
    depends_on:
      - PostgreSQL
    container_name: back
    build: ./back
    image: back
    volumes:
      - ./back:/app/back
    ports:
      - 4000:4000
    restart: always
    init: true
    networks:
      - Wow
    environment:
      - API42_UID=${API42_UID}
      - API42_SECRET=${API42_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - FRONT_URL=${FRONT_URL}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - TWO_FACTOR_NAME=${TWO_FACTOR_NAME}
  front:
    depends_on:
      - back
    container_name: front
    build: ./front
    image: front
    volumes:
      - ./front:/app/front
    ports:
      - 3000:3000
    restart: always
    init: true
    networks:
      - Wow
    environment:
    - REACT_APP_API42_UID=${API42_UID}
    - REACT_APP_REDIRECT_URI=${REDIRECT_URI}
    - REACT_APP_BACK=${APP_BACK}


  adminer :
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - Wow

networks:
  Wow:
    driver: bridge
    external: false
