version: '3'
services:
  PostgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports: 
      - "5432:5432"
    networks:
      - Wow

  back:
    depends_on:
      - PostgreSQL
    container_name: back
    build: ./back
    image: back
    volumes:
      - ./back:/app
    ports: 
      - 4000:4000
    restart: always
    init: true
    networks:
      - Wow

  front:
    depends_on:
      - back
    container_name: front
    build: ./front
    image: front
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    restart: always
    init: true
    networks:
      - Wow
  
  adminer :
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    networks: 
      - Wow

networks:
  Wow:
    driver: bridge
    external: false
