
version: '3'

services:
  PostgreSQL:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports: 
      - "5432:5432"


      #
      #back:
      #    depends_on:
      #      - PostgreSQL
      #    image: back
      #    container_name: back
      #    restart: always
      #    init: true
      #
      #
      #front :
      #    depends_on:
      #      - back
      #    build: ./srcs/front
      #    image: front
      #    container_name: front
      #    restart: always
      #    ports:
      #      - 4000:4000
      #


